### PR TITLE
Support osx_arm64 (M1 Macs)

### PR DESCRIPTION
**Pull request by robintw**
Try to support osx_arm64 (M1 Macs).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by robintw** [comment]
@conda-forge-admin, please rerender

**Comment by robintw** [comment]
This seems to be working for the M1 build now (at least, the CI passes - I haven't actually tested it on a M1 Mac as I don't have access to one quite yet) - but the Windows build is failing.

The error given in the Windows build is:

```
(%BUILD_PREFIX%) %SRC_DIR%>cmake -G "MSYS Makefiles" -D CMAKE_INSTALL_PREFIX=%PREFIX%\Library %SRC_DIR% 
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_AR was not found, please set to archive program. 
-- Configuring incomplete, errors occurred!
```

Does anyone know if there is some other package I need to install to get the MSYS Makefiles working?

Interestingly, this has worked previously (and I haven't changed the Windows configuration at all) - but it failed in a previous PR ([here](https://github.com/conda-forge/sixs-feedstock/pull/9) when GCC was updated - and it never got round to being fixed and merged. It seems like it's some sort of change in the conda-forge repository structure/code (whatever is updated when you 'rerender') that is causing it. That PR is basically outdated by this PR, but it'd be good to be able to work out what is going on for the Windows build.

@ocefpaf Sorry to bother you, but you've been really helpful before with issues here. Do you have any idea what I can do to fix this Windows build? Or do you know anyone who is experienced with CMake builds on Windows on conda-forge?

**Comment by ocefpaf** [comment]
> @ocefpaf Sorry to bother you, but you've been really helpful before with issues here. Do you have any idea what I can do to fix this Windows build? Or do you know anyone who is experienced with CMake builds on Windows on conda-forge?

I'm terrible with Windows and Cmake :smile: but I'm OK merging this without it if you want b/c you don't really need a new Windows package here, right? We can open an issue to track this and fix in another PR.

**Comment by robintw** [comment]
I didn't realise that would work @ocefpaf! If we do this, will conda-forge keep the old Windows version available for install as usual, and just update the other packages (including the new M1 package)?

**Comment by ocefpaf** [comment]
> I didn't realise that would work @ocefpaf! If we do this, will conda-forge keep the old Windows version available for install as usual, and just update the other packages (including the new M1 package)?

Yep. We never remove what was already built. Do you mind opening an issue to track the Windows problem here? Merging this...

**Pull request merged**
