### PR TITLE
add support for linux-aarch64 builds (i.e. Nvidia Jetson)

### PR DESCRIPTION
**Pull request by christhechris**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hi team, I'm trying to add linux_aarch64 support to the build in order to make it easier to use py6s on devices like the Nvidia Jetson etc. The changes seems to be all ok when testing using 'build-locally.py'.

### CODE REVIEW

**Comment by robintw** [comment]
Thanks @christhechris - this all looks good. Is this related to PR #16? I don't know anything about aarch64, but they seem to be trying to do the same thing.

All the Azure Pipelines CI seems to have passed here, but the 'drone pr' CI (whatever that is), still seems to be pending - whereas on the other PR, the Travis build has failed.

Out of interest, as the Py6S author, can I ask what particular sort of work you're doing with Py6S? I'm always interested to hear of use cases, and trying to use it on a Nvidia Jetson sounds interesting!

**Comment by christhechris** [comment]
hi @robintw yup I think #16 was triggered by a another thing I did (https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2095 following advise here https://conda-forge.org/docs/maintainer/infrastructure.html#drone-io). I think it is essentially the same as this PR except I skipped ppc, but missing the addition of make as a dependancy to make the build happy.

The travis and drone.io are the default CIs for linux_ppc64le and linux_aarch64 versions.

I think we could add the linux_ppc64le line to this PR and then #16 would be redundant. I'll try and do that now.

**Comment by christhechris** [comment]
@conda-forge-admin, please rerender

**Comment by christhechris** [comment]
@robintw On our use of py6s, I'm postdoc at sydney uni working on custom hyper spectral instruments, including an open source design. As part of that a couple of our PhD candidates are working on an open source data reduction pipeline, and are using Py6S to get their final reflectance measurements.  Its not public yet, but our first release should be out in a just a few weeks! (https://github.com/openhsi/)

Part of the goal it is to get everything running on an autonomous system, hence the use of the Jetson.

**Comment by christhechris** [comment]
@conda-forge-admin, please rerender

**Comment by robintw** [comment]
@christhechris The PR all looks good now, and everything passes. I'll merge this one and close the other one.

Thanks for letting me know what you're up-to with Py6S - sounds fascinating.

**Pull request merged**
